### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-data-validator#70]
- [x] webignition/basil-dom-identifier-factory#34
- [x] webignition/basil-identifier-analyser#22
- [x] webignition/basil-validation-result#5
- [x] webignition/basil-parser#105
- [x] webignition/basil-resolver#49
